slide03後半
OmeSatoFoundation/ome-doc pull request #507
Opened 2024-06-05 15:39 UTC by motegi210

2024-06-05 15:40 UTC, motegi210 commented
https://github.com/OmeSatoFoundation/ome-doc/issues/496

2024-06-06 06:02 UTC, RollMan requested changes
タイプセットでエラーが出るようです。

```
docker run --rm -v ${pwd}:/workdir ome-doc /bin/sh -c 'cd 03; llmk;'
(中略)
(./slide03.out) (./slide03.out)
(/usr/local/texlive/2023/texmf-dist/tex/latex/translator/translator-basic-dicti
onary-English.dict)
(/usr/local/texlive/2023/texmf-dist/tex/latex/translator/translator-bibliograph
y-dictionary-English.dict)
(/usr/local/texlive/2023/texmf-dist/tex/latex/translator/translator-environment
-dictionary-English.dict)
(/usr/local/texlive/2023/texmf-dist/tex/latex/translator/translator-months-dict
ionary-English.dict)
(/usr/local/texlive/2023/texmf-dist/tex/latex/translator/translator-numbers-dic
tionary-English.dict)
(/usr/local/texlive/2023/texmf-dist/tex/latex/translator/translator-theorem-dic
tionary-English.dict) (./slide03.nav) (./slide_contents/shell_command.tex)
(./slide_contents/sensorboard.tex
(/usr/local/texlive/2023/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2023/texmf-dist/tex/latex/amsfonts/umsb.fd) [1{/usr/local/t
exlive/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]

LaTeX Warning: File `../images/chap03/sensors_name.png' not found on input line
 31.


! Package luatex.def Error: File `../images/chap03/sensors_name.png' not found:
 using draft setting.

See the luatex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.31 \end{frame}

?
! Emergency stop.
 ...

l.31 \end{frame}

 17545 words of node memory still in use:
   78 hlist, 11 vlist, 8 rule, 14 local_par, 5 dir, 18 math, 224 glue, 14 kern,
 60 penalty, 100 glyph, 5811 attribute, 80 glue_spec, 598 attribute_list, 5 tem
p, 7 if_stack, 1 write, 89 user_defined, 12 pdf_literal, 54 pdf_colorstack node
s
   avail lists: 1:17,2:1959,3:341,4:578,5:119,6:42,7:659,8:1,9:458,10:15
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on slide03.log.
llmk error: Fail running lualatex --shell-escape --cnf-line='TEXINPUTS=.;../texmf//;' "slide03.tex" (exit code: 1)
PS G:\ome-doc> git status
On branch slide03_2
Your branch is up to date with 'origin/slide03_2'.

nothing to commit, working tree clean
PS G:\ome-doc> git rev-parse HEAD
6e449eacaba573735d12ceef0170b89b6129d396
```

2024-06-06 06:56 UTC, motegi210 commented
スライド用に新たな写真を追加したのですが、それらをaddしていませんでした。先ほどpushしました。

2024-06-06 07:17 UTC, RollMan approved these changes
タイプセットは通りました。

2024-06-13 10:29 UTC, merged