第3回　echoコマンドの説明を追加
OmeSatoFoundation/ome-doc pull request #542
Opened 2024-06-30 08:41 UTC by motegi210

https://github.com/OmeSatoFoundation/ome-doc/issues/538
p27, p28
- 外側の$()の説明
- 内側の()の説明
- 中身が数字になった場合の結果
- 問題のフォーマットをそろえる

2024-06-30 08:55 UTC, RollMan commented on 03/contents/chap03_150_AdvancedCommands.tex
> +このように電卓を使って計算したいものを目の前のコンピュータに計算してもらえたら便利ですね
句点があったほうが良さそうです。

2024-06-30 08:55 UTC, RollMan commented on 03/contents/chap03_150_AdvancedCommands.tex
> +echoコマンドの他の使い方を見てみましょう。echo \$((式))と打つと計算結果を出力してくれます。
改段落をして次の文「ここで内側にも……」と段落をつなげると良さそうです。

2024-07-02 02:19 UTC, RollMan requested changes

2024-07-02 02:19 UTC, RollMan commented on 03/contents/chap03_150_AdvancedCommands.tex
> +        次の文章の「like」を「love」に置き換えましょう。\\%
フォーマッタをかけてくれたのだと思いますが、すぐ (セルフ) マージできない場合は他のユーザーが同時編集している可能性がある部分に変更を加えないほうがよいです。さもないと意味のないコンフリクトが出ます。

2024-07-04 07:13 UTC, hogenimushi commented on 03/contents/chap03_150_AdvancedCommands.tex
> +        次の文章の「like」を「love」に置き換えましょう。\\%
こちらの方、解決したつもりなのですが、この後どうすればよいでしょうか。

2024-07-04 08:25 UTC, RollMan commented on 03/contents/chap03_150_AdvancedCommands.tex
> +        次の文章の「like」を「love」に置き換えましょう。\\%
まだ master と diff があり auto-merge 可能かわかりませんが、とりあえず私の change request は resolve して PR から merge できるようにしておきます。

内容の是非は diff をなくすか (無理矢理) merge して確認しないとわからないかと思います。

2024-07-04 08:25 UTC, RollMan approved these changes

2024-07-04 08:27 UTC, merged

2024-07-04 08:30 UTC, RollMan commented on 03/contents/chap03_150_AdvancedCommands.tex
> +        次の文章の「like」を「love」に置き換えましょう。\\%
sed 周辺は問題なさそうです。